# title: Software Security
# description: "#Code4Sec Week, #Day1  #NEIS0736 #NECS0736 #Software Security"
# show_downloads: true
# google_analytics: true

# theme: jekyll-theme-architect
# theme: jekyll-theme-hacker
theme: jekyll-theme-midnight
# theme: jekyll-theme-modernist
# theme: jekyll-theme-slate
# theme: jekyll-theme-tactile